### ISSUE TITLE
"Unexpected identifier" SyntaxError thrown by meiosis-setup

### ISSUE THREAD

**Issue by pwagner** [AdditionApps/polaris-form-builder#4]
I wanted to give the Polaris Form Builder a try, but unfortunately I'm stuck with the following error after installing it:

```
node_modules/meiosis-setup/mergerino/index.js:1
┃ import commonSetup from "../common";
┃        ^^^^^^^^^^^
┃ 
┃ SyntaxError: Unexpected identifier
```

I've tried it with node versions 10 and 12 (v12.18.3) and version 1.2.0 as well as the current version of this repo.

**Steps to reproduce the error:**
1) Create a new node app using the Shopify App CLI
2) Install polaris-form-builder
3) Add a form to the app according to readme

**Comment by fourstacks** [comment]
Hi @pwagner - sorry for slow reply.  I don't actually use the shopify CLI to develop apps but I do know that in order to use the form builder package you'd need a build process like rollup or webpack.  

Not 100% sure what the build process used in the CLI is but that error looks like it might be in that ballpark.  I certainly don't see anything like that when compiling my JS (or TS) using webpack.  I'll add a note in the readme about this.

**Comment by pwagner** [comment]
The [node app](https://github.com/Shopify/shopify-app-node) created by Shopify App CLI actually uses webpack for the build process, via nextjs. Maybe its [default babel presets](https://github.com/vercel/next.js/blob/canary/packages/next/build/babel/preset.ts) are causing a problem here. I'll dig deeper when I have time, I'd really like to play around with the form-builder. Thanks for your reply!
